#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DatabaseWarehouse")]
public partial class DatabaseWarehouseDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 可扩展性方法定义
  partial void OnCreated();
  partial void InsertTableWarehouse(TableWarehouse instance);
  partial void UpdateTableWarehouse(TableWarehouse instance);
  partial void DeleteTableWarehouse(TableWarehouse instance);
  #endregion
	
	public DatabaseWarehouseDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DatabaseWarehouseConnectionString1"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DatabaseWarehouseDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DatabaseWarehouseDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DatabaseWarehouseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DatabaseWarehouseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<TableWarehouse> TableWarehouse
	{
		get
		{
			return this.GetTable<TableWarehouse>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TableWarehouse")]
public partial class TableWarehouse : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _仓库名称;
	
	private string _联系方式;
	
	private string _简码;
	
	private string _简称;
	
	private string _备注;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void On仓库名称Changing(string value);
    partial void On仓库名称Changed();
    partial void On联系方式Changing(string value);
    partial void On联系方式Changed();
    partial void On简码Changing(string value);
    partial void On简码Changed();
    partial void On简称Changing(string value);
    partial void On简称Changed();
    partial void On备注Changing(string value);
    partial void On备注Changed();
    #endregion
	
	public TableWarehouse()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_仓库名称", DbType="NVarChar(50)")]
	public string 仓库名称
	{
		get
		{
			return this._仓库名称;
		}
		set
		{
			if ((this._仓库名称 != value))
			{
				this.On仓库名称Changing(value);
				this.SendPropertyChanging();
				this._仓库名称 = value;
				this.SendPropertyChanged("仓库名称");
				this.On仓库名称Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_联系方式", DbType="NVarChar(50)")]
	public string 联系方式
	{
		get
		{
			return this._联系方式;
		}
		set
		{
			if ((this._联系方式 != value))
			{
				this.On联系方式Changing(value);
				this.SendPropertyChanging();
				this._联系方式 = value;
				this.SendPropertyChanged("联系方式");
				this.On联系方式Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_简码", DbType="NChar(10)")]
	public string 简码
	{
		get
		{
			return this._简码;
		}
		set
		{
			if ((this._简码 != value))
			{
				this.On简码Changing(value);
				this.SendPropertyChanging();
				this._简码 = value;
				this.SendPropertyChanged("简码");
				this.On简码Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_简称", DbType="NChar(10)")]
	public string 简称
	{
		get
		{
			return this._简称;
		}
		set
		{
			if ((this._简称 != value))
			{
				this.On简称Changing(value);
				this.SendPropertyChanging();
				this._简称 = value;
				this.SendPropertyChanged("简称");
				this.On简称Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_备注", DbType="NVarChar(MAX)")]
	public string 备注
	{
		get
		{
			return this._备注;
		}
		set
		{
			if ((this._备注 != value))
			{
				this.On备注Changing(value);
				this.SendPropertyChanging();
				this._备注 = value;
				this.SendPropertyChanged("备注");
				this.On备注Changed();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
